// ============================================================================
// S&P 500 COMPLETE DATASET - Part 2 (Additional Companies)
// All verified IR links - continues from real-data.ts
// ============================================================================

export const SP500_ADDITIONAL: Record<string, {
    name: string;
    sector: string;
    ir: string;
    cik?: string;
}> = {
    // ========== TECH - Additional ==========
    "ORCL": { name: "Oracle Corporation", sector: "Technology", ir: "https://investor.oracle.com/", cik: "1341439" },
    "IBM": { name: "IBM", sector: "Technology", ir: "https://www.ibm.com/investor/", cik: "51143" },
    "CSCO": { name: "Cisco Systems", sector: "Technology", ir: "https://investor.cisco.com/", cik: "858877" },
    "ADBE": { name: "Adobe Inc.", sector: "Technology", ir: "https://www.adobe.com/investor-relations.html", cik: "796343" },
    "ACN": { name: "Accenture", sector: "Technology", ir: "https://investor.accenture.com/", cik: "1467373" },
    "TXN": { name: "Texas Instruments", sector: "Technology", ir: "https://investor.ti.com/", cik: "97476" },
    "INTU": { name: "Intuit Inc.", sector: "Technology", ir: "https://investors.intuit.com/", cik: "896878" },
    "AMAT": { name: "Applied Materials", sector: "Technology", ir: "https://ir.appliedmaterials.com/", cik: "6951" },
    "LRCX": { name: "Lam Research", sector: "Technology", ir: "https://investor.lamresearch.com/", cik: "707549" },
    "ADI": { name: "Analog Devices", sector: "Technology", ir: "https://investor.analog.com/", cik: "6281" },
    "KLAC": { name: "KLA Corporation", sector: "Technology", ir: "https://ir.kla.com/", cik: "319201" },
    "SNPS": { name: "Synopsys Inc.", sector: "Technology", ir: "https://investor.synopsys.com/", cik: "883241" },
    "CDNS": { name: "Cadence Design", sector: "Technology", ir: "https://www.cadence.com/en_US/home/company/investor-relations.html", cik: "813672" },
    "FTNT": { name: "Fortinet Inc.", sector: "Technology", ir: "https://investor.fortinet.com/", cik: "1262039" },
    "WDAY": { name: "Workday Inc.", sector: "Technology", ir: "https://investor.workday.com/", cik: "1327811" },
    "TEAM": { name: "Atlassian Corp", sector: "Technology", ir: "https://investors.atlassian.com/", cik: "1650372" },
    "ANSS": { name: "ANSYS Inc.", sector: "Technology", ir: "https://investors.ansys.com/", cik: "1013462" },
    "ADSK": { name: "Autodesk Inc.", sector: "Technology", ir: "https://investors.autodesk.com/", cik: "769397" },
    "CTSH": { name: "Cognizant Technology", sector: "Technology", ir: "https://investors.cognizant.com/", cik: "1058290" },
    "NXPI": { name: "NXP Semiconductors", sector: "Technology", ir: "https://investors.nxp.com/", cik: "1413447" },
    "ON": { name: "ON Semiconductor", sector: "Technology", ir: "https://investor.onsemi.com/", cik: "1097864" },
    "MPWR": { name: "Monolithic Power", sector: "Technology", ir: "https://www.monolithicpower.com/investors", cik: "1280452" },
    "GEN": { name: "Gen Digital", sector: "Technology", ir: "https://investor.gendigital.com/", cik: "849399" },
    "ENPH": { name: "Enphase Energy", sector: "Technology", ir: "https://investor.enphase.com/", cik: "1463101" },
    "FSLR": { name: "First Solar", sector: "Technology", ir: "https://investor.firstsolar.com/", cik: "1274494" },
    "HPQ": { name: "HP Inc.", sector: "Technology", ir: "https://investor.hp.com/", cik: "47217" },
    "HPE": { name: "HP Enterprise", sector: "Technology", ir: "https://investors.hpe.com/", cik: "1645590" },
    "DELL": { name: "Dell Technologies", sector: "Technology", ir: "https://investors.delltechnologies.com/", cik: "1571996" },
    "KEYS": { name: "Keysight Technologies", sector: "Technology", ir: "https://investor.keysight.com/", cik: "1601046" },
    "EPAM": { name: "EPAM Systems", sector: "Technology", ir: "https://investors.epam.com/", cik: "1352010" },
    "AKAM": { name: "Akamai Technologies", sector: "Technology", ir: "https://www.akamai.com/company/investor-relations", cik: "1086222" },
    "CDW": { name: "CDW Corporation", sector: "Technology", ir: "https://investor.cdw.com/", cik: "1402057" },
    "JNPR": { name: "Juniper Networks", sector: "Technology", ir: "https://investor.juniper.net/", cik: "1043604" },
    "ZBRA": { name: "Zebra Technologies", sector: "Technology", ir: "https://investors.zebra.com/", cik: "877212" },
    "SWKS": { name: "Skyworks Solutions", sector: "Technology", ir: "https://investors.skyworksinc.com/", cik: "4127" },
    "QRVO": { name: "Qorvo Inc.", sector: "Technology", ir: "https://investors.qorvo.com/", cik: "1604778" },
    "TER": { name: "Teradyne Inc.", sector: "Technology", ir: "https://investors.teradyne.com/", cik: "97210" },
    "NTAP": { name: "NetApp Inc.", sector: "Technology", ir: "https://investors.netapp.com/", cik: "1002047" },
    "WDC": { name: "Western Digital", sector: "Technology", ir: "https://investor.wdc.com/", cik: "106040" },
    "STX": { name: "Seagate Technology", sector: "Technology", ir: "https://investors.seagate.com/", cik: "1137789" },
    "FFIV": { name: "F5 Inc.", sector: "Technology", ir: "https://www.f5.com/company/investor-relations", cik: "1048695" },
    "PTC": { name: "PTC Inc.", sector: "Technology", ir: "https://investor.ptc.com/", cik: "857005" },
    "PAYC": { name: "Paycom Software", sector: "Technology", ir: "https://investors.paycom.com/", cik: "1590955" },
    "PAYX": { name: "Paychex Inc.", sector: "Technology", ir: "https://investor.paychex.com/", cik: "723531" },
    "TRMB": { name: "Trimble Inc.", sector: "Technology", ir: "https://investor.trimble.com/", cik: "864749" },
    "VRSN": { name: "VeriSign Inc.", sector: "Technology", ir: "https://investor.verisign.com/", cik: "1014473" },

    // ========== FINANCIALS - Additional ==========
    "USB": { name: "U.S. Bancorp", sector: "Financial", ir: "https://ir.usbank.com/", cik: "36104" },
    "PNC": { name: "PNC Financial", sector: "Financial", ir: "https://investor.pnc.com/", cik: "713676" },
    "TFC": { name: "Truist Financial", sector: "Financial", ir: "https://ir.truist.com/", cik: "92230" },
    "COF": { name: "Capital One", sector: "Financial", ir: "https://investor.capitalone.com/", cik: "927628" },
    "SPGI": { name: "S&P Global", sector: "Financial", ir: "https://investor.spglobal.com/", cik: "64040" },
    "MCO": { name: "Moody's Corporation", sector: "Financial", ir: "https://ir.moodys.com/", cik: "1059556" },
    "CME": { name: "CME Group", sector: "Financial", ir: "https://investor.cmegroup.com/", cik: "1156375" },
    "ICE": { name: "Intercontinental Exchange", sector: "Financial", ir: "https://ir.theice.com/", cik: "1571949" },
    "CB": { name: "Chubb Limited", sector: "Financial", ir: "https://investors.chubb.com/", cik: "896159" },
    "MMC": { name: "Marsh McLennan", sector: "Financial", ir: "https://www.marshmclennan.com/investor-relations.html", cik: "62709" },
    "AON": { name: "Aon plc", sector: "Financial", ir: "https://investor.aon.com/", cik: "315293" },
    "AJG": { name: "Arthur J. Gallagher", sector: "Financial", ir: "https://investor.ajg.com/", cik: "354190" },
    "AFL": { name: "Aflac Inc.", sector: "Financial", ir: "https://investors.aflac.com/", cik: "4977" },
    "MET": { name: "MetLife Inc.", sector: "Financial", ir: "https://investor.metlife.com/", cik: "1099219" },
    "PRU": { name: "Prudential Financial", sector: "Financial", ir: "https://investor.prudential.com/", cik: "1137774" },
    "AIG": { name: "American International Group", sector: "Financial", ir: "https://www.aig.com/about-us/investor-relations", cik: "5272" },
    "TRV": { name: "Travelers Companies", sector: "Financial", ir: "https://investor.travelers.com/", cik: "86312" },
    "ALL": { name: "Allstate Corp", sector: "Financial", ir: "https://www.allstateinvestors.com/", cik: "899051" },
    "PGR": { name: "Progressive Corp", sector: "Financial", ir: "https://investors.progressive.com/", cik: "80661" },
    "FITB": { name: "Fifth Third Bancorp", sector: "Financial", ir: "https://ir.53.com/", cik: "35527" },
    "MTB": { name: "M&T Bank", sector: "Financial", ir: "https://ir.mtb.com/", cik: "36270" },
    "KEY": { name: "KeyCorp", sector: "Financial", ir: "https://investor.key.com/", cik: "91576" },
    "RF": { name: "Regions Financial", sector: "Financial", ir: "https://ir.regions.com/", cik: "1281761" },
    "HBAN": { name: "Huntington Bancshares", sector: "Financial", ir: "https://ir.huntington.com/", cik: "49196" },
    "CFG": { name: "Citizens Financial", sector: "Financial", ir: "https://investor.citizensbank.com/", cik: "759944" },
    "CINF": { name: "Cincinnati Financial", sector: "Financial", ir: "https://www.cinfin.com/investors", cik: "20286" },
    "DFS": { name: "Discover Financial", sector: "Financial", ir: "https://investorrelations.discover.com/", cik: "1393612" },
    "SYF": { name: "Synchrony Financial", sector: "Financial", ir: "https://investors.synchrony.com/", cik: "1601712" },
    "NDAQ": { name: "Nasdaq Inc.", sector: "Financial", ir: "https://ir.nasdaq.com/", cik: "1120193" },
    "CBOE": { name: "Cboe Global Markets", sector: "Financial", ir: "https://ir.cboe.com/", cik: "1374310" },
    "MSCI": { name: "MSCI Inc.", sector: "Financial", ir: "https://ir.msci.com/", cik: "1408198" },
    "TROW": { name: "T. Rowe Price", sector: "Financial", ir: "https://investors.troweprice.com/", cik: "1113169" },
    "BEN": { name: "Franklin Resources", sector: "Financial", ir: "https://www.franklinresources.com/investor", cik: "38777" },
    "IVZ": { name: "Invesco Ltd", sector: "Financial", ir: "https://ir.invesco.com/", cik: "914208" },
    "AMG": { name: "Affiliated Managers", sector: "Financial", ir: "https://ir.amg.com/", cik: "1004434" },
    "RJF": { name: "Raymond James", sector: "Financial", ir: "https://www.raymondjames.com/investor-relations", cik: "720005" },
    "SIVB": { name: "SVB Financial", sector: "Financial", ir: "https://ir.svb.com/", cik: "719739" },
    "ZION": { name: "Zions Bancorp", sector: "Financial", ir: "https://investor.zionsbancorporation.com/", cik: "109380" },
    "CMA": { name: "Comerica Inc.", sector: "Financial", ir: "https://investor.comerica.com/", cik: "28412" },
    "FRC": { name: "First Republic Bank", sector: "Financial", ir: "https://ir.firstrepublic.com/", cik: "1132979" },
    "NTRS": { name: "Northern Trust", sector: "Financial", ir: "https://www.northerntrust.com/about-us/investor-relations", cik: "73124" },
    "STT": { name: "State Street Corp", sector: "Financial", ir: "https://investors.statestreet.com/", cik: "93751" },
    "BK": { name: "Bank of New York Mellon", sector: "Financial", ir: "https://www.bnymellon.com/us/en/investor-relations.html", cik: "1390777" },

    // ========== HEALTHCARE - Additional ==========
    "DHR": { name: "Danaher Corp", sector: "Healthcare", ir: "https://investors.danaher.com/", cik: "313616" },
    "MDT": { name: "Medtronic plc", sector: "Healthcare", ir: "https://investorrelations.medtronic.com/", cik: "1613103" },
    "SYK": { name: "Stryker Corp", sector: "Healthcare", ir: "https://www.stryker.com/us/en/about/investor-relations.html", cik: "310764" },
    "BSX": { name: "Boston Scientific", sector: "Healthcare", ir: "https://www.bostonscientific.com/investor", cik: "885725" },
    "EW": { name: "Edwards Lifesciences", sector: "Healthcare", ir: "https://ir.edwards.com/", cik: "1099800" },
    "ZBH": { name: "Zimmer Biomet", sector: "Healthcare", ir: "https://investor.zimmerbiomet.com/", cik: "1136869" },
    "BDX": { name: "Becton Dickinson", sector: "Healthcare", ir: "https://investors.bd.com/", cik: "10795" },
    "BAX": { name: "Baxter International", sector: "Healthcare", ir: "https://www.baxter.com/investors", cik: "10456" },
    "A": { name: "Agilent Technologies", sector: "Healthcare", ir: "https://investor.agilent.com/", cik: "1090872" },
    "DXCM": { name: "DexCom Inc.", sector: "Healthcare", ir: "https://investors.dexcom.com/", cik: "1093557" },
    "IQV": { name: "IQVIA Holdings", sector: "Healthcare", ir: "https://ir.iqvia.com/", cik: "1478242" },
    "IDXX": { name: "IDEXX Laboratories", sector: "Healthcare", ir: "https://www.idexx.com/en/about-idexx/investor-relations/", cik: "874716" },
    "ALGN": { name: "Align Technology", sector: "Healthcare", ir: "https://investor.aligntech.com/", cik: "1097149" },
    "HOLX": { name: "Hologic Inc.", sector: "Healthcare", ir: "https://investors.hologic.com/", cik: "859737" },
    "RMD": { name: "ResMed Inc.", sector: "Healthcare", ir: "https://investor.resmed.com/", cik: "943819" },
    "MTD": { name: "Mettler-Toledo", sector: "Healthcare", ir: "https://investor.mt.com/", cik: "1037646" },
    "WAT": { name: "Waters Corporation", sector: "Healthcare", ir: "https://ir.waters.com/", cik: "1000697" },
    "TECH": { name: "Bio-Techne Corp", sector: "Healthcare", ir: "https://investors.bio-techne.com/", cik: "858254" },
    "WST": { name: "West Pharmaceutical", sector: "Healthcare", ir: "https://investors.westpharma.com/", cik: "105770" },
    "PODD": { name: "Insulet Corp", sector: "Healthcare", ir: "https://investor.insulet.com/", cik: "1145197" },
    "VRTX": { name: "Vertex Pharmaceuticals", sector: "Healthcare", ir: "https://investors.vrtx.com/", cik: "875320" },
    "REGN": { name: "Regeneron Pharmaceuticals", sector: "Healthcare", ir: "https://investor.regeneron.com/", cik: "872589" },
    "BIIB": { name: "Biogen Inc.", sector: "Healthcare", ir: "https://investors.biogen.com/", cik: "875045" },
    "ILMN": { name: "Illumina Inc.", sector: "Healthcare", ir: "https://investor.illumina.com/", cik: "1110803" },
    "ZTS": { name: "Zoetis Inc.", sector: "Healthcare", ir: "https://investor.zoetis.com/", cik: "1555280" },
    "CI": { name: "Cigna Group", sector: "Healthcare", ir: "https://www.cigna.com/about-us/investors", cik: "1739940" },
    "ELV": { name: "Elevance Health", sector: "Healthcare", ir: "https://ir.elevancehealth.com/", cik: "1156039" },
    "HUM": { name: "Humana Inc.", sector: "Healthcare", ir: "https://humana.gcs-web.com/", cik: "49071" },
    "CNC": { name: "Centene Corp", sector: "Healthcare", ir: "https://investors.centene.com/", cik: "1071739" },
    "MOH": { name: "Molina Healthcare", sector: "Healthcare", ir: "https://investors.molinahealthcare.com/", cik: "1179929" },
    "HCA": { name: "HCA Healthcare", sector: "Healthcare", ir: "https://investor.hcahealthcare.com/", cik: "860730" },
    "CVS": { name: "CVS Health", sector: "Healthcare", ir: "https://investors.cvshealth.com/", cik: "64803" },
    "WBA": { name: "Walgreens Boots Alliance", sector: "Healthcare", ir: "https://investor.walgreensbootsalliance.com/", cik: "1618921" },
    "MCK": { name: "McKesson Corp", sector: "Healthcare", ir: "https://investor.mckesson.com/", cik: "927653" },
    "CAH": { name: "Cardinal Health", sector: "Healthcare", ir: "https://ir.cardinalhealth.com/", cik: "721371" },
    "ABC": { name: "AmerisourceBergen", sector: "Healthcare", ir: "https://investor.amerisourcebergen.com/", cik: "1140859" },
    "HSIC": { name: "Henry Schein", sector: "Healthcare", ir: "https://investor.henryschein.com/", cik: "1000228" },

    // ========== CONSUMER - Additional ==========
    "DG": { name: "Dollar General", sector: "Consumer", ir: "https://investor.dollargeneral.com/", cik: "29534" },
    "DLTR": { name: "Dollar Tree", sector: "Consumer", ir: "https://investor.dollartree.com/", cik: "935703" },
    "ROST": { name: "Ross Stores", sector: "Consumer", ir: "https://investors.rossstores.com/", cik: "745732" },
    "TJX": { name: "TJX Companies", sector: "Consumer", ir: "https://www.tjx.com/investors", cik: "109198" },
    "BBY": { name: "Best Buy Co.", sector: "Consumer", ir: "https://investors.bestbuy.com/", cik: "764478" },
    "EBAY": { name: "eBay Inc.", sector: "Consumer", ir: "https://investors.ebay.com/", cik: "1065088" },
    "ETSY": { name: "Etsy Inc.", sector: "Consumer", ir: "https://investors.etsy.com/", cik: "1370637" },
    "EXPE": { name: "Expedia Group", sector: "Consumer", ir: "https://ir.expediagroup.com/", cik: "1324424" },
    "ORLY": { name: "O'Reilly Automotive", sector: "Consumer", ir: "https://corporate.oreillyauto.com/investor-relations", cik: "898173" },
    "AZO": { name: "AutoZone Inc.", sector: "Consumer", ir: "https://investors.autozone.com/", cik: "866787" },
    "KMX": { name: "CarMax Inc.", sector: "Consumer", ir: "https://investors.carmax.com/", cik: "1170010" },
    "GPC": { name: "Genuine Parts", sector: "Consumer", ir: "https://investor.genpt.com/", cik: "40987" },
    "TSCO": { name: "Tractor Supply", sector: "Consumer", ir: "https://investor.tractorsupply.com/", cik: "916365" },
    "ULTA": { name: "Ulta Beauty", sector: "Consumer", ir: "https://www.ultabeauty.com/investor", cik: "1403568" },
    "EL": { name: "Estee Lauder", sector: "Consumer", ir: "https://www.elcompanies.com/en/investors", cik: "1001250" },
    "CL": { name: "Colgate-Palmolive", sector: "Consumer", ir: "https://investor.colgatepalmolive.com/", cik: "21665" },
    "CLX": { name: "Clorox Company", sector: "Consumer", ir: "https://investors.thecloroxcompany.com/", cik: "21076" },
    "KMB": { name: "Kimberly-Clark", sector: "Consumer", ir: "https://investor.kimberly-clark.com/", cik: "55785" },
    "CHD": { name: "Church & Dwight", sector: "Consumer", ir: "https://investor.churchdwight.com/", cik: "313927" },
    "SJM": { name: "J.M. Smucker", sector: "Consumer", ir: "https://investor.jmsmucker.com/", cik: "91419" },
    "GIS": { name: "General Mills", sector: "Consumer", ir: "https://investors.generalmills.com/", cik: "40704" },
    "K": { name: "Kellanova", sector: "Consumer", ir: "https://investor.kellanova.com/", cik: "55067" },
    "CAG": { name: "Conagra Brands", sector: "Consumer", ir: "https://www.conagrabrands.com/investor-relations", cik: "23217" },
    "HRL": { name: "Hormel Foods", sector: "Consumer", ir: "https://investor.hormelfoods.com/", cik: "48465" },
    "CPB": { name: "Campbell Soup", sector: "Consumer", ir: "https://investor.campbellsoupcompany.com/", cik: "16732" },
    "TAP": { name: "Molson Coors", sector: "Consumer", ir: "https://ir.molsoncoors.com/", cik: "24545" },
    "STZ": { name: "Constellation Brands", sector: "Consumer", ir: "https://www.cbrands.com/investors", cik: "16918" },
    "BF.B": { name: "Brown-Forman", sector: "Consumer", ir: "https://www.brown-forman.com/investors", cik: "14693" },
    "MNST": { name: "Monster Beverage", sector: "Consumer", ir: "https://www.monsterbevcorp.com/investors", cik: "865752" },
    "KDP": { name: "Keurig Dr Pepper", sector: "Consumer", ir: "https://investor.keurigdrpepper.com/", cik: "1418135" },
    "HSY": { name: "Hershey Co.", sector: "Consumer", ir: "https://investors.thehersheycompany.com/", cik: "47111" },
    "MDLZ": { name: "Mondelez International", sector: "Consumer", ir: "https://ir.mondelezinternational.com/", cik: "1103982" },
    "KR": { name: "Kroger Company", sector: "Consumer", ir: "https://ir.kroger.com/", cik: "56873" },
    "SYY": { name: "Sysco Corp", sector: "Consumer", ir: "https://investor.sysco.com/", cik: "96021" },
    "YUM": { name: "Yum! Brands", sector: "Consumer", ir: "https://investors.yum.com/", cik: "1041061" },
    "DRI": { name: "Darden Restaurants", sector: "Consumer", ir: "https://investor.darden.com/", cik: "940944" },
    "CMG": { name: "Chipotle Mexican Grill", sector: "Consumer", ir: "https://ir.chipotle.com/", cik: "1058090" },
    "DPZ": { name: "Domino's Pizza", sector: "Consumer", ir: "https://ir.dominos.com/", cik: "1286681" },
    "WING": { name: "Wingstop Inc.", sector: "Consumer", ir: "https://ir.wingstop.com/", cik: "1636222" },
    "QSR": { name: "Restaurant Brands Intl", sector: "Consumer", ir: "https://investor.rbi.com/", cik: "1618755" },
    "HLT": { name: "Hilton Worldwide", sector: "Consumer", ir: "https://ir.hilton.com/", cik: "1585689" },
    "H": { name: "Hyatt Hotels", sector: "Consumer", ir: "https://investors.hyatt.com/", cik: "1468174" },
    "WH": { name: "Wyndham Hotels", sector: "Consumer", ir: "https://investor.wyndhamhotels.com/", cik: "1722684" },
    "MGM": { name: "MGM Resorts", sector: "Consumer", ir: "https://investors.mgmresorts.com/", cik: "789570" },
    "LVS": { name: "Las Vegas Sands", sector: "Consumer", ir: "https://investor.sands.com/", cik: "1300514" },
    "WYNN": { name: "Wynn Resorts", sector: "Consumer", ir: "https://investor.wynnresorts.com/", cik: "1174922" },
    "RCL": { name: "Royal Caribbean", sector: "Consumer", ir: "https://investor.royalcaribbean.com/", cik: "884887" },
    "CCL": { name: "Carnival Corp", sector: "Consumer", ir: "https://www.carnivalcorp.com/investor-relations", cik: "815097" },
    "NCLH": { name: "Norwegian Cruise Line", sector: "Consumer", ir: "https://investor.ncl.com/", cik: "1513761" },
    "F": { name: "Ford Motor", sector: "Consumer", ir: "https://shareholder.ford.com/", cik: "37996" },
    "GM": { name: "General Motors", sector: "Consumer", ir: "https://investor.gm.com/", cik: "1467858" },
    "RIVN": { name: "Rivian Automotive", sector: "Consumer", ir: "https://rivian.com/investors", cik: "1874178" },
    "LCID": { name: "Lucid Group", sector: "Consumer", ir: "https://ir.lucidmotors.com/", cik: "1811210" },

    // ========== INDUSTRIALS - Additional ==========
    "MMM": { name: "3M Company", sector: "Industrial", ir: "https://investors.3m.com/", cik: "66740" },
    "EMR": { name: "Emerson Electric", sector: "Industrial", ir: "https://www.emerson.com/en-us/investors", cik: "32604" },
    "ETN": { name: "Eaton Corp", sector: "Industrial", ir: "https://www.eaton.com/us/en-us/company/investor-relations.html", cik: "31462" },
    "ROK": { name: "Rockwell Automation", sector: "Industrial", ir: "https://www.rockwellautomation.com/en-us/company/investor-relations.html", cik: "1024478" },
    "ABB": { name: "ABB Ltd", sector: "Industrial", ir: "https://global.abb/group/en/investors", cik: "52747" },
    "AME": { name: "AMETEK Inc.", sector: "Industrial", ir: "https://investors.ametek.com/", cik: "1037868" },
    "ITW": { name: "Illinois Tool Works", sector: "Industrial", ir: "https://investor.itw.com/", cik: "49826" },
    "PH": { name: "Parker-Hannifin", sector: "Industrial", ir: "https://investors.parker.com/", cik: "76334" },
    "DOV": { name: "Dover Corp", sector: "Industrial", ir: "https://investors.dovercorporation.com/", cik: "29905" },
    "IR": { name: "Ingersoll Rand", sector: "Industrial", ir: "https://investors.irco.com/", cik: "1699150" },
    "CARR": { name: "Carrier Global", sector: "Industrial", ir: "https://ir.carrier.com/", cik: "1783180" },
    "OTIS": { name: "Otis Worldwide", sector: "Industrial", ir: "https://investors.otis.com/", cik: "1781335" },
    "SWK": { name: "Stanley Black & Decker", sector: "Industrial", ir: "https://ir.stanleyblackanddecker.com/", cik: "93556" },
    "GWW": { name: "W.W. Grainger", sector: "Industrial", ir: "https://invest.grainger.com/", cik: "277135" },
    "FAST": { name: "Fastenal Company", sector: "Industrial", ir: "https://investor.fastenal.com/", cik: "815556" },
    "PCAR": { name: "PACCAR Inc.", sector: "Industrial", ir: "https://www.paccar.com/investors/", cik: "75362" },
    "CMI": { name: "Cummins Inc.", sector: "Industrial", ir: "https://investor.cummins.com/", cik: "26172" },
    "WAB": { name: "Westinghouse Air Brake", sector: "Industrial", ir: "https://ir.wabteccorp.com/", cik: "943452" },
    "NSC": { name: "Norfolk Southern", sector: "Industrial", ir: "https://norfolksouthern.investorroom.com/", cik: "702165" },
    "CSX": { name: "CSX Corp", sector: "Industrial", ir: "https://investors.csx.com/", cik: "277948" },
    "EXPD": { name: "Expeditors Intl", sector: "Industrial", ir: "https://investor.expeditors.com/", cik: "746515" },
    "CHRW": { name: "C.H. Robinson", sector: "Industrial", ir: "https://investor.chrobinson.com/", cik: "1043277" },
    "JBHT": { name: "J.B. Hunt Transport", sector: "Industrial", ir: "https://www.jbhunt.com/investor-relations/", cik: "728535" },
    "XPO": { name: "XPO Logistics", sector: "Industrial", ir: "https://investors.xpo.com/", cik: "1166003" },
    "ODFL": { name: "Old Dominion Freight", sector: "Industrial", ir: "https://ir.odfl.com/", cik: "878927" },
    "GD": { name: "General Dynamics", sector: "Industrial", ir: "https://investorrelations.gd.com/", cik: "40533" },
    "NOC": { name: "Northrop Grumman", sector: "Industrial", ir: "https://investor.northropgrumman.com/", cik: "1133421" },
    "HII": { name: "Huntington Ingalls", sector: "Industrial", ir: "https://investor.huntingtoningalls.com/", cik: "1501585" },
    "LHX": { name: "L3Harris Technologies", sector: "Industrial", ir: "https://www.l3harris.com/investors", cik: "202058" },
    "TDG": { name: "TransDigm Group", sector: "Industrial", ir: "https://ir.transdigm.com/", cik: "1260221" },
    "HWM": { name: "Howmet Aerospace", sector: "Industrial", ir: "https://www.howmet.com/investors/", cik: "4281" },
    "WM": { name: "Waste Management", sector: "Industrial", ir: "https://investors.wm.com/", cik: "823768" },
    "RSG": { name: "Republic Services", sector: "Industrial", ir: "https://investor.republicservices.com/", cik: "1060391" },
    "WCN": { name: "Waste Connections", sector: "Industrial", ir: "https://investors.wasteconnections.com/", cik: "1318220" },
    "VRSK": { name: "Verisk Analytics", sector: "Industrial", ir: "https://investor.verisk.com/", cik: "1442145" },
    "ROL": { name: "Rollins Inc.", sector: "Industrial", ir: "https://ir.rollins.com/", cik: "84839" },
    "CTAS": { name: "Cintas Corp", sector: "Industrial", ir: "https://www.cintas.com/investors/", cik: "723254" },
    "J": { name: "Jacobs Solutions", sector: "Industrial", ir: "https://invest.jacobs.com/", cik: "52988" },
    "PWR": { name: "Quanta Services", sector: "Industrial", ir: "https://investors.quantaservices.com/", cik: "1060083" },

    // ========== ENERGY - Additional ==========
    "EOG": { name: "EOG Resources", sector: "Energy", ir: "https://investors.eogresources.com/", cik: "821189" },
    "PXD": { name: "Pioneer Natural Resources", sector: "Energy", ir: "https://investors.pxd.com/", cik: "1038357" },
    "DVN": { name: "Devon Energy", sector: "Energy", ir: "https://investors.devonenergy.com/", cik: "1090012" },
    "FANG": { name: "Diamondback Energy", sector: "Energy", ir: "https://ir.diamondbackenergy.com/", cik: "1539838" },
    "MPC": { name: "Marathon Petroleum", sector: "Energy", ir: "https://ir.marathonpetroleum.com/", cik: "1510295" },
    "VLO": { name: "Valero Energy", sector: "Energy", ir: "https://investorrelations.valero.com/", cik: "1035002" },
    "PSX": { name: "Phillips 66", sector: "Energy", ir: "https://investor.phillips66.com/", cik: "1534701" },
    "HAL": { name: "Halliburton", sector: "Energy", ir: "https://ir.halliburton.com/", cik: "45012" },
    "BKR": { name: "Baker Hughes", sector: "Energy", ir: "https://investors.bakerhughes.com/", cik: "1701605" },
    "OKE": { name: "ONEOK Inc.", sector: "Energy", ir: "https://www.oneok.com/investors", cik: "1039684" },
    "WMB": { name: "Williams Companies", sector: "Energy", ir: "https://investor.williams.com/", cik: "107263" },
    "KMI": { name: "Kinder Morgan", sector: "Energy", ir: "https://ir.kindermorgan.com/", cik: "1506307" },
    "ET": { name: "Energy Transfer", sector: "Energy", ir: "https://ir.energytransfer.com/", cik: "1276187" },
    "TRGP": { name: "Targa Resources", sector: "Energy", ir: "https://investor.targaresources.com/", cik: "1389170" },
    "LNG": { name: "Cheniere Energy", sector: "Energy", ir: "https://lngir.cheniere.com/", cik: "3570" },

    // ========== UTILITIES - Additional ==========
    "AEP": { name: "American Electric Power", sector: "Utilities", ir: "https://www.aep.com/investors/", cik: "4904" },
    "D": { name: "Dominion Energy", sector: "Utilities", ir: "https://investors.dominionenergy.com/", cik: "715957" },
    "XEL": { name: "Xcel Energy", sector: "Utilities", ir: "https://investors.xcelenergy.com/", cik: "72903" },
    "EXC": { name: "Exelon Corp", sector: "Utilities", ir: "https://www.exeloncorp.com/investor-relations", cik: "1109357" },
    "SRE": { name: "Sempra Energy", sector: "Utilities", ir: "https://investor.sempra.com/", cik: "1032208" },
    "PCG": { name: "PG&E Corp", sector: "Utilities", ir: "https://investor.pgecorp.com/", cik: "75488" },
    "ED": { name: "Consolidated Edison", sector: "Utilities", ir: "https://investor.conedison.com/", cik: "23632" },
    "WEC": { name: "WEC Energy Group", sector: "Utilities", ir: "https://investor.wecenergygroup.com/", cik: "783325" },
    "ES": { name: "Eversource Energy", sector: "Utilities", ir: "https://investor.eversource.com/", cik: "72741" },
    "DTE": { name: "DTE Energy", sector: "Utilities", ir: "https://investor.dteenergy.com/", cik: "936340" },
    "PPL": { name: "PPL Corp", sector: "Utilities", ir: "https://www.pplweb.com/investors/", cik: "922224" },
    "FE": { name: "FirstEnergy Corp", sector: "Utilities", ir: "https://www.firstenergycorp.com/investor.html", cik: "1031296" },
    "ETR": { name: "Entergy Corp", sector: "Utilities", ir: "https://www.entergy.com/investor_relations/", cik: "65984" },
    "CMS": { name: "CMS Energy", sector: "Utilities", ir: "https://www.cmsenergy.com/investor-relations", cik: "811156" },
    "CNP": { name: "CenterPoint Energy", sector: "Utilities", ir: "https://investors.centerpointenergy.com/", cik: "1130310" },
    "NI": { name: "NiSource Inc.", sector: "Utilities", ir: "https://www.nisource.com/investors", cik: "1111711" },
    "EIX": { name: "Edison International", sector: "Utilities", ir: "https://www.edison.com/investors", cik: "827052" },
    "AES": { name: "AES Corp", sector: "Utilities", ir: "https://investor.aes.com/", cik: "874761" },
    "AWK": { name: "American Water Works", sector: "Utilities", ir: "https://ir.amwater.com/", cik: "1410636" },
    "EVRG": { name: "Evergy Inc.", sector: "Utilities", ir: "https://investors.evergy.com/", cik: "1711269" },

    // ========== REAL ESTATE - Additional ==========
    "CCI": { name: "Crown Castle", sector: "Real Estate", ir: "https://investor.crowncastle.com/", cik: "1051470" },
    "O": { name: "Realty Income", sector: "Real Estate", ir: "https://investor.realtyincome.com/", cik: "726728" },
    "WELL": { name: "Welltower Inc.", sector: "Real Estate", ir: "https://welltower.com/investors/", cik: "766704" },
    "SPG": { name: "Simon Property Group", sector: "Real Estate", ir: "https://investors.simon.com/", cik: "1063761" },
    "PSA": { name: "Public Storage", sector: "Real Estate", ir: "https://investors.publicstorage.com/", cik: "1393311" },
    "DLR": { name: "Digital Realty", sector: "Real Estate", ir: "https://investor.digitalrealty.com/", cik: "1297996" },
    "AVB": { name: "AvalonBay Communities", sector: "Real Estate", ir: "https://investors.avaloncommunities.com/", cik: "915912" },
    "EQR": { name: "Equity Residential", sector: "Real Estate", ir: "https://investors.equityapartments.com/", cik: "906107" },
    "ESS": { name: "Essex Property Trust", sector: "Real Estate", ir: "https://investors.essex.com/", cik: "920522" },
    "MAA": { name: "Mid-America Apartment", sector: "Real Estate", ir: "https://investor.maac.com/", cik: "912595" },
    "UDR": { name: "UDR Inc.", sector: "Real Estate", ir: "https://ir.udr.com/", cik: "74208" },
    "VTR": { name: "Ventas Inc.", sector: "Real Estate", ir: "https://ir.ventasreit.com/", cik: "740260" },
    "ARE": { name: "Alexandria Real Estate", sector: "Real Estate", ir: "https://investor.are.com/", cik: "1035443" },
    "BXP": { name: "Boston Properties", sector: "Real Estate", ir: "https://investors.bxp.com/", cik: "1037540" },
    "SLG": { name: "SL Green Realty", sector: "Real Estate", ir: "https://slgreen.com/investors/", cik: "1040971" },
    "VNO": { name: "Vornado Realty", sector: "Real Estate", ir: "https://investors.vno.com/", cik: "899629" },
    "KIM": { name: "Kimco Realty", sector: "Real Estate", ir: "https://investors.kimcorealty.com/", cik: "879101" },
    "REG": { name: "Regency Centers", sector: "Real Estate", ir: "https://investors.regencycenters.com/", cik: "910606" },
    "FRT": { name: "Federal Realty", sector: "Real Estate", ir: "https://investors.federalrealty.com/", cik: "34903" },
    "HST": { name: "Host Hotels & Resorts", sector: "Real Estate", ir: "https://ir.hosthotels.com/", cik: "1070750" },
    "PEAK": { name: "Healthpeak Properties", sector: "Real Estate", ir: "https://ir.healthpeak.com/", cik: "765880" },
    "CPT": { name: "Camden Property Trust", sector: "Real Estate", ir: "https://investors.camdenliving.com/", cik: "906345" },
    "IRM": { name: "Iron Mountain", sector: "Real Estate", ir: "https://investors.ironmountain.com/", cik: "1020569" },
    "SBAC": { name: "SBA Communications", sector: "Real Estate", ir: "https://ir.sbasite.com/", cik: "1034054" },
    "CBRE": { name: "CBRE Group", sector: "Real Estate", ir: "https://ir.cbre.com/", cik: "1138118" },

    // ========== MATERIALS - Additional ==========
    "LIN": { name: "Linde plc", sector: "Materials", ir: "https://investors.linde.com/", cik: "1707925" },
    "APD": { name: "Air Products & Chemicals", sector: "Materials", ir: "https://investors.airproducts.com/", cik: "2969" },
    "SHW": { name: "Sherwin-Williams", sector: "Materials", ir: "https://investors.sherwin-williams.com/", cik: "89800" },
    "ECL": { name: "Ecolab Inc.", sector: "Materials", ir: "https://investor.ecolab.com/", cik: "31462" },
    "DD": { name: "DuPont de Nemours", sector: "Materials", ir: "https://investors.dupont.com/", cik: "1666700" },
    "DOW": { name: "Dow Inc.", sector: "Materials", ir: "https://investors.dow.com/", cik: "1751788" },
    "NEM": { name: "Newmont Corp", sector: "Materials", ir: "https://www.newmont.com/investors/", cik: "1164727" },
    "FCX": { name: "Freeport-McMoRan", sector: "Materials", ir: "https://investors.fcx.com/", cik: "831259" },
    "NUE": { name: "Nucor Corp", sector: "Materials", ir: "https://investor.nucor.com/", cik: "73309" },
    "STLD": { name: "Steel Dynamics", sector: "Materials", ir: "https://ir.steeldynamics.com/", cik: "1022671" },
    "VMC": { name: "Vulcan Materials", sector: "Materials", ir: "https://ir.vulcanmaterials.com/", cik: "1396009" },
    "MLM": { name: "Martin Marietta", sector: "Materials", ir: "https://ir.martinmarietta.com/", cik: "916076" },
    "PPG": { name: "PPG Industries", sector: "Materials", ir: "https://investor.ppg.com/", cik: "79879" },
    "ALB": { name: "Albemarle Corp", sector: "Materials", ir: "https://investors.albemarle.com/", cik: "915913" },
    "CE": { name: "Celanese Corp", sector: "Materials", ir: "https://investors.celanese.com/", cik: "1306830" },
    "EMN": { name: "Eastman Chemical", sector: "Materials", ir: "https://investors.eastman.com/", cik: "915389" },
    "LYB": { name: "LyondellBasell", sector: "Materials", ir: "https://www.lyondellbasell.com/en/investors/", cik: "1489393" },
    "CF": { name: "CF Industries", sector: "Materials", ir: "https://investors.cfindustries.com/", cik: "1324404" },
    "MOS": { name: "Mosaic Company", sector: "Materials", ir: "https://investors.mosaicco.com/", cik: "1285785" },
    "FMC": { name: "FMC Corp", sector: "Materials", ir: "https://investors.fmc.com/", cik: "37785" },
    "IFF": { name: "International Flavors", sector: "Materials", ir: "https://ir.iff.com/", cik: "51253" },
    "IP": { name: "International Paper", sector: "Materials", ir: "https://investor.internationalpaper.com/", cik: "51434" },
    "PKG": { name: "Packaging Corp", sector: "Materials", ir: "https://investor.packagingcorp.com/", cik: "75677" },
    "WRK": { name: "WestRock Co", sector: "Materials", ir: "https://ir.westrock.com/", cik: "1636023" },
    "SEE": { name: "Sealed Air", sector: "Materials", ir: "https://ir.sealedair.com/", cik: "1012100" },
    "AVY": { name: "Avery Dennison", sector: "Materials", ir: "https://www.averydennison.com/en/home/investors.html", cik: "8818" },
    "BALL": { name: "Ball Corp", sector: "Materials", ir: "https://ir.ball.com/", cik: "9389" },
    "AMCR": { name: "Amcor plc", sector: "Materials", ir: "https://www.amcor.com/investors", cik: "1748790" },
    // ========== POPULAR / RETAIL ==========
    "GME": { name: "GameStop Corp", sector: "Consumer", ir: "https://gamestop.gcs-web.com/", cik: "1326380" },
    "AMC": { name: "AMC Entertainment", sector: "Communication Services", ir: "https://investor.amctheatres.com/", cik: "1411579" },
    "HOOD": { name: "Robinhood Markets", sector: "Financial", ir: "https://investors.robinhood.com/", cik: "1783879" },
    "RDDT": { name: "Reddit Inc.", sector: "Communication Services", ir: "https://investor.redditinc.com/", cik: "1713445" },
    "PLUG": { name: "Plug Power", sector: "Energy", ir: "https://www.ir.plugpower.com/", cik: "1093691" },
    "DKNG": { name: "DraftKings Inc.", sector: "Consumer", ir: "https://draftkings.gcs-web.com/", cik: "1772757" },
    "ROKU": { name: "Roku Inc.", sector: "Communication Services", ir: "https://investor.roku.com/", cik: "1128455" },
    "PATH": { name: "UiPath Inc.", sector: "Technology", ir: "https://ir.uipath.com/", cik: "1734714" },
    "AI": { name: "C3.ai Inc.", sector: "Technology", ir: "https://ir.c3.ai/", cik: "1577526" },
};
