import { NextRequest, NextResponse } from 'next/server';
import { Resend } from 'resend';

const resend = process.env.RESEND_API_KEY ? new Resend(process.env.RESEND_API_KEY) : null;

export async function POST(request: NextRequest) {
    try {
        const { email, name } = await request.json();

        if (!email || !name) {
            return NextResponse.json(
                { error: 'Email and name are required' },
                { status: 400 }
            );
        }



        // Send email notification to admin
        const adminEmail = 'saziz4250@gmail.com';
        const date = new Date().toLocaleString('en-US', {
            month: 'short',
            day: 'numeric',
            year: 'numeric',
            hour: 'numeric',
            minute: '2-digit',
            timeZoneName: 'short'
        });

        const emailHTML = `
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="margin: 0; padding: 0; font-family: -apple-system, system-ui, sans-serif; background-color: #f8f9fa;">
    <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff;">
        <!-- Header -->
        <div style="background: linear-gradient(135deg, #2563eb 0%, #8b5cf6 100%); padding: 32px 24px;">
            <h1 style="margin: 0; color: #ffffff; font-size: 20px; font-weight: 700;">
                🎯 New Novai Pro Waitlist Signup
            </h1>
            <p style="margin: 4px 0 0 0; color: #e0e7ff; font-size: 13px;">
                ${date}
            </p>
        </div>

        <!-- Content -->
        <div style="padding: 32px 24px;">
            <div style="background-color: #f8f9fa; border-left: 4px solid #2563eb; padding: 20px; margin-bottom: 24px;">
                <h2 style="margin: 0 0 16px 0; font-size: 16px; font-weight: 600; color: #0f172a;">
                    Contact Information
                </h2>
                <table style="width: 100%; border-collapse: collapse;">
                    <tr>
                        <td style="padding: 8px 0; font-size: 14px; color: #6b7280; font-weight: 600;">Name:</td>
                        <td style="padding: 8px 0; font-size: 14px; color: #0f172a;">${name}</td>
                    </tr>
                    <tr>
                        <td style="padding: 8px 0; font-size: 14px; color: #6b7280; font-weight: 600;">Email:</td>
                        <td style="padding: 8px 0; font-size: 14px; color: #0f172a;">${email}</td>
                    </tr>
                    <tr>
                        <td style="padding: 8px 0; font-size: 14px; color: #6b7280; font-weight: 600;">Timestamp:</td>
                        <td style="padding: 8px 0; font-size: 14px; color: #0f172a;">${new Date().toISOString()}</td>
                    </tr>
                </table>
            </div>

            <div style="background-color: #eff6ff; border-radius: 8px; padding: 16px; margin-bottom: 24px;">
                <p style="margin: 0; font-size: 13px; color: #1e40af; line-height: 1.5;">
                    <strong>Action Required:</strong> This user is interested in Novai Pro features. Consider adding them to your outreach list when Pro features launch.
                </p>
            </div>

            <p style="margin: 0; font-size: 13px; color: #6b7280;">
                This notification was automatically generated by the Novai Intelligence platform.
            </p>
        </div>

        <!-- Footer -->
        <div style="padding: 20px 24px; background-color: #0f172a; text-align: center;">
            <p style="margin: 0; font-size: 11px; color: #94a3b8;">
                NOVAI INTELLIGENCE • Pro Waitlist System
            </p>
        </div>
    </div>
</body>
</html>
        `.trim();

        // Send email via Resend
        let emailSent = false;
        if (resend) {
            try {
                const data = await resend.emails.send({
                    from: 'Novai Intelligence <onboarding@resend.dev>',
                    to: [adminEmail],
                    subject: `🎯 New Pro Waitlist Signup: ${name}`,
                    html: emailHTML
                });
                console.log('✅ Pro waitlist notification sent to admin via Resend:', data);
                emailSent = true;
            } catch (resendError) {
                console.error('⚠️ Resend failed, falling back to FormSubmit:', resendError);
            }
        } else {
            console.log('ℹ️ RESEND_API_KEY not found. Using FormSubmit.co fallback.');
        }

        // Fallback to FormSubmit.co if Resend failed or key is missing
        if (!emailSent) {
            try {
                await fetch('https://formsubmit.co/ajax/saziz4250@gmail.com', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'Accept': 'application/json'
                    },
                    body: JSON.stringify({
                        _subject: `🎯 New Pro Waitlist Signup: ${name}`,
                        name: name,
                        email: email,
                        message: `New Pro Waitlist Signup\nName: ${name}\nEmail: ${email}`,
                        _template: 'table',
                        _captcha: "false"
                    })
                });
                console.log('✅ Pro waitlist notification sent via FormSubmit.co fallback');
            } catch (fallbackError) {
                console.error('⚠️ All email delivery methods failed:', fallbackError);
            }
        }

        // Log to console as backup
        console.log('=== PRO WAITLIST SIGNUP ===');
        console.log(`Name: ${name}`);
        console.log(`Email: ${email}`);
        console.log(`Timestamp: ${new Date().toISOString()}`);
        console.log('===========================');

        return NextResponse.json({
            success: true,
            message: 'Successfully joined waitlist',
        });
    } catch (error) {
        console.error('Error processing waitlist signup:', error);
        return NextResponse.json(
            { error: 'Failed to process signup' },
            { status: 500 }
        );
    }
}

